# Generated by Django 4.2 on 2025-07-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("parameter", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ClimateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("jan", models.FloatField(blank=True, null=True)),
                ("feb", models.FloatField(blank=True, null=True)),
                ("mar", models.FloatField(blank=True, null=True)),
                ("apr", models.FloatField(blank=True, null=True)),
                ("may", models.FloatField(blank=True, null=True)),
                ("jun", models.FloatField(blank=True, null=True)),
                ("jul", models.FloatField(blank=True, null=True)),
                ("aug", models.FloatField(blank=True, null=True)),
                ("sep", models.FloatField(blank=True, null=True)),
                ("oct", models.FloatField(blank=True, null=True)),
                ("nov", models.FloatField(blank=True, null=True)),
                ("dec", models.FloatField(blank=True, null=True)),
                ("win", models.FloatField(blank=True, null=True)),
                ("spr", models.FloatField(blank=True, null=True)),
                ("sum", models.FloatField(blank=True, null=True)),
                ("aut", models.FloatField(blank=True, null=True)),
                ("ann", models.FloatField(blank=True, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.region",
                    ),
                ),
            ],
        ),
    ]
