# Generated by Django 4.2 on 2025-07-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("name", "parameter")},
        ),
    ]
