# Generated by Django 4.2 on 2025-07-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("weather_app", "0002_alter_region_name_alter_region_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateDataSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("source", models.TextField(blank=True)),
                ("last_updated", models.CharField(blank=True, max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.region",
                    ),
                ),
            ],
            options={
                "unique_together": {("region",)},
            },
        ),
    ]
