# Generated by Django 4.2 on 2025-07-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather_app", "0003_climatedatasummary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="climatedatasummary",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="climatedatasummary",
            name="source",
        ),
    ]
